## travis for R-devel taken from sinhrks/ggfortify

language: r
warnings_are_errors: true
sudo: required

matrix:
  include:
    - env: RVER=STD
    - env: RVER=DEV

r_binary_packages:
  - rmarkdown

r_github_packages:
  - jimhester/covr

before_install:
  - if [[ "$RVER" == "DEV" ]]; then
      sh install_rdevel.sh;
    fi
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" >> ~/.Rprofile

after_success:
  - Rscript -e 'library(covr);coveralls()'
