language: r
cache: packages

r:
  - oldrel
  - release
  - devel

r_github_packages:
  - r-lib/covr

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get -qq update
  - sudo apt-get install libgmp3-dev

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
